# Scikit-Learn Algorithms

### 1.6 Nearest Neighbors (최근접 이웃)


sklearn.neighbors는 지도와 비지도 이웃에 기초한 학습방법을 제공한다. 
비지도 최근접 이웃은 다양한 학습과 spectral clustering의 기초가 된다. 
지도 이웃 기반 학습은 두가지가 있다. 이산레이블을 포함한 자료에 대한 분류와 연속레이블 포함한 자료에 대한 회귀분석이다. 

최근접이웃방법의 원칙은 새로운 점과 가장 가까운 거리에 있는 사전 정의된 수의 훈련 샘플을 찾아 이것으로 부터 레이블을 예측하는 것이다. 샘플의 수는 사용자 정의상수(k-최근접이웃학습)이거나 점의 local density에 따라 달라질수 있다. 거리는 일반적으로 미터법으로 측정할 수 있다. 표준 유클리드 거리가 가장 일반적이다. 이웃기반방법은 모든 훈련자료를 기억하기 때문에 비일반화 기계학습방법으로 알려져 있다. 

이러한 단순함에도 불구하고, 최근접이웃은 손으로 쓴 숫자와 위성 이미지 장면을 포함한 많은 수의 분류와 회귀 문제에서 성공했다. 비모수적 방법이기 때문에 의사결정 경계가 매우 불규칙한 분류 상황에서 종종 성공한다.

sklearn.nears의 클래스는 NumPy 배열이나 spipy.sparse 행렬을 입력으로 처리할 수 있습니다. 밀도 행렬의 경우 가능한 거리 행렬 수가 많이 지원됩니다. 희박행렬(sparse matrices)의 경우 검색을 위해 임의 Minkowski 행렬이 지원된다.

### 1.6.1. Unsupervised Nearest Neighbors(비지도 최근점 이웃)

이 알고리즘은 인접한 세 가지 알고리즘인 BallTree, KDTree 및 Sklearn.metrics.pairwise의 루틴을 기반으로 하는 Brute-force 알고리즘에 대한 균일한 인터페이스 역할을 한다.

In [1]:
#Finding the Nearest Neighbors
from sklearn.neighbors import NearestNeighbors
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(X)
distances, indices = nbrs.kneighbors(X)
indices

array([[0, 1],
       [1, 0],
       [2, 1],
       [3, 4],
       [4, 3],
       [5, 4]], dtype=int64)

In [2]:
distances

array([[ 0.        ,  1.        ],
       [ 0.        ,  1.        ],
       [ 0.        ,  1.41421356],
       [ 0.        ,  1.        ],
       [ 0.        ,  1.        ],
       [ 0.        ,  1.41421356]])

In [3]:
nbrs.kneighbors_graph(X).toarray()

array([[ 1.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  1.]])